# Generated by Django 3.1.1 on 2020-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200930_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=4.99, max_digits=7),
        ),
    ]
