# Generated by Django 3.1.1 on 2020-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20201005_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
