# Generated by Django 3.1.1 on 2020-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201005_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_paymentid',
            field=models.CharField(default='', max_length=270),
        ),
    ]
