# Generated by Django 3.1.1 on 2020-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20201024_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_2',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
