# Generated by Django 3.1.1 on 2020-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
