# Generated by Django 3.1.1 on 2020-10-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0002_bag_delivery_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=4.99, max_digits=7),
        ),
    ]
