# Generated by Django 3.1.1 on 2020-10-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0003_auto_20201005_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='delivery_total',
        ),
    ]
