# Generated by Django 3.1.1 on 2020-09-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
