# Generated by Django 3.1.1 on 2020-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201014_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time_updated',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Average'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=3),
        ),
    ]
