# Generated by Django 3.1.1 on 2020-10-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_state'),
        ('products', '0011_auto_20201020_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists', to='profiles.userprofile'),
        ),
    ]
